### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by soupglasses** [DeterminateSystems/nuenv#16]
Currently this project has no license file, making it unclear if this is a project that is meant to be used or contributed to outside of DetSys.

**Comment by grahamc** [comment]
We’ll apply the MIT license in the next few days, and we consider it MIT
already. 

Thanks for opening the issue, oops :)

On September 9, 2023, GitHub ***@***.***> wrote:
> Currently this project has no license file, making it unclear if this
> is a project that is meant to be used or contributed to outside of
> DetSys.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/DeterminateSystems/nuenv/issues/16>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAASXLFGUJSK3INRZ2ZZNJTXZROVZANCNFSM6AAAAAA4RNMDGA>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by soupglasses** [comment]
Kind bump for @grahamc as this seems to have slipped through the cracks.
